Controllers/AttendanceSessionController.cs
using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Unicode;
using System.Threading.Tasks;
using baam.Config;
using baam.Model.Api;
using baam.Model.Db;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using ApiAttendanceSession = baam.Model.Api.AttendanceSession;
using DbAttendanceSession = baam.Model.Db.AttendanceSession;

namespace baam.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AttendanceSessionController : ControllerBase
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly ILogger<AttendanceSessionController> _logger;
        private readonly AttendanceSessionConfiguration _config;

        public AttendanceSessionController(ApplicationDbContext context, ILogger<AttendanceSessionController> logger, 
            IOptions<AttendanceSessionConfiguration> config)
        {
            _dbContext = context;
            _logger = logger;
            _config = config.Value;
        }

        [HttpGet]
        public IActionResult GetSessions()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            return Ok(_dbContext.AttendanceSessions.Where(s => !s.Running && s.Instructor == HttpContext.User.GetUpn())
                .AsEnumerable()
                .Select(s => 
                    new ListingAttendanceSession
                    {
                        Title = s.Title,
                        StartDate = s.StartDate,
                        SessionCode = s.SessionCode
                    }).ToArray());
        }
        
        [HttpGet("{code}")]
        public IActionResult GetSession([FromRoute] string code)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var session = _dbContext.AttendanceSessions
                .Where(_ => _.Id == Base36.Decode(code))
                .Include(_ => _.Attendance)
                .SingleOrDefault();
            
            if (session == null)
                return NotFound();

            if (session.Instructor != HttpContext.User.GetUpn())
                return Forbid();



            var attendance = session.Attendance
                .GroupBy(m => m.Student)
                .OrderBy(g => g.First().Time)
                .Select(g => (g.Key,
                        Enumerable.Range(0, session.StagesStarted)
                            .Select(s => g.Any(m => m.Stage == s))
                            .ToImmutableArray()
                    )
                ).ToImmutableArray();
            
            return Ok(new ApiAttendanceSession
            {
                Title = session.Title,
                SessionCode = session.SessionCode,
                AttendanceMarks = attendance,
                LastStageIndex = session.LastStageIndex,
            });
        }

        [HttpPost("getOrStart")]
        public async Task<IActionResult> GetOrStartSession()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var user = HttpContext.User.GetUpn();
            
            var res = _dbContext.AttendanceSessions
                .Select(s => new {s, s.Attendance.Count})
                .SingleOrDefault(t => t.s.Running && t.s.Instructor == user);

            var session = res?.s;

            if (res?.Count == 0)
            {
                _dbContext.Remove(res!.s);
                session = null;
            }
            
            if (session == null)
            {
                session = new DbAttendanceSession
                {
                    Instructor = user,
                    Running = true,
                    StagesCompleted = 0,
                    StartDate = DateTime.UtcNow,
                    AttendanceSeed = Utils.MakeSecureSeed(),
                    Title = "Untitled attendance session"
                };
                
                await _dbContext.AttendanceSessions.AddAsync(session);
                await _dbContext.SaveChangesAsync();
            }
            
            _logger.LogInformation($"Starting session {session.Id}");

            return Ok(new AttendanceSessionStartResult
            {
                Title = session.Title,
                AttendanceSeed = session.AttendanceSeed,
                SessionCode = session.SessionCode,
                InitialIteration = session.GetFirstNonStaleIteration(_config.SecretCodeIntervalMs!.Value),
                SecretCodeIntervalMs = _config.SecretCodeIntervalMs!.Value,
                CurrentStage = session.LastStageIndex,
            });
        }

        [HttpPost("{code}/stop")]
        public async Task<IActionResult> StopSession([FromRoute] string code)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var user = HttpContext.User.GetUpn();
            
            var session = _dbContext.AttendanceSessions.SingleOrDefault(s => s.Running && s.Instructor == user
                && s.Id == Base36.Decode(code));

            if (session == null)
                return NotFound();

            session.Running = false;
            session.StagesCompleted++; // fixme: Races possible. Nobody cares, but optimistic concurrency should be used

            await _dbContext.SaveChangesAsync();
            return Ok();
        }

        
        [HttpPut("{code}")]
        public async Task<IActionResult> UpdateSession([FromRoute] string code, [FromBody] AttendanceSessionUpdate update)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var session = await _dbContext.AttendanceSessions.FindAsync(checked((int)Base36.Decode(code)));
            
            if (session == null)
                return NotFound();

            if (session.Instructor != HttpContext.User.GetUpn())
                return Forbid();

            session.Title = update.Title;

            await _dbContext.SaveChangesAsync();

            return Ok();
        }
        

        private string Hash(string seed, int index)
        {
            var ms = new MemoryStream();
            ms.Write(Encoding.UTF8.GetBytes(seed));
            ms.Write(BitConverter.GetBytes(index));
            
            var hash = SHA1.HashData(ms.ToArray());
            return Convert.ToBase64String(hash[..6]).Replace('/', '_').Replace("=", "");
        }
        
        private bool ValidateChallenge(DbAttendanceSession session, string secretCode, DateTime submissionTime)
        {
            var hash = secretCode[..8];
            var index = checked((int)Base36.Decode(secretCode[8..]));

            var realHash = Hash(session.AttendanceSeed, index);

            if (hash != realHash)
                return false;
            
            var expectedRevealTime = session.StartDate + TimeSpan.FromMilliseconds(_config.SecretCodeIntervalMs!.Value) * index;
            var expectedRotateTime = expectedRevealTime + TimeSpan.FromMilliseconds(_config.SecretCodeIntervalMs.Value);
            TimeSpan difference;
            if (submissionTime < expectedRevealTime)
                difference = expectedRevealTime - submissionTime;
            else if (submissionTime > expectedRotateTime)
                difference = submissionTime - expectedRotateTime;
            else
                difference = TimeSpan.Zero;
            
            // difference shows by how much the submission time differs from either the reveal time or rotate time

            var res = difference < TimeSpan.FromMilliseconds(_config.ChallengeSubmissionTimeToleranceMs!.Value);

            _logger.LogDebug($"Difference is {difference}; {(res ? "pass" : "fail")}");

            
            return res;
        }

        [HttpPost("{code}/submitChallenge")]
        public async Task<IActionResult> SubmitChallenge([FromRoute] string code, [FromBody] string secretCode)
        {
            var submissionTime = DateTime.UtcNow;

            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            
            var user = HttpContext.User.GetUpn();
            var sessionId = checked((int) Base36.Decode(code));
            
            var session = await _dbContext.AttendanceSessions.FindAsync(sessionId);
            
            if (session == null)
            {
                _logger.LogDebug($"Session {code} does not exists");
                return new NotFoundResult();
            }

            if (!session.Running)
            {
                _logger.LogDebug($"Session {code} is not running");
                return new NotFoundResult();
            }

            if (!ValidateChallenge(session, secretCode, submissionTime))
            {
                _logger.LogDebug($"Challenge result {secretCode} validation failed");
                return new ForbidResult();
            }
            
            _logger.LogDebug($"Challenge result {secretCode} validation succeeded, giving an attendance mark");

            var mark = _dbContext.AttendanceMarks.SingleOrDefault(_ => _.SessionId == sessionId
                                                                       && _.Student == user
                                                                       && _.Stage == session.StagesCompleted);
            
            // silently ignore existing marks
            if (mark != null) 
                return Ok(code);
            
            await _dbContext.AttendanceMarks.AddAsync(new AttendanceMark
            {
                Session = session,
                Student = user,
                Manual = false,
                Stage = session.StagesCompleted,
            });

            await _dbContext.SaveChangesAsync();

Pages/AttendanceCheck.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using baam.Model.Db;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace baam.Pages
{
    public class AttendanceCheckModel : PageModel
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public AttendanceCheckModel(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }
    }
}

Pages/AttendanceSession.cshtml.cs
using System.Linq;
using baam.Helpers;
using baam.Model.Api;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AttendanceSession = baam.Model.Db.AttendanceSession;

namespace baam.Pages
{
    public class AttendanceSessionModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly ExportHelper _exportHelper;

        public AttendanceSessionModel(ApplicationDbContext dbContext, ExportHelper exportHelper)
        {
            _dbContext = dbContext;
            _exportHelper = exportHelper;
        }

        public AttendanceSession Session { get; set; } = null!;
        
        [BindProperty] 
        public ExportParams ExportParams { get; set; } = null!;
        
        public IActionResult OnGet(string code)
        {
            var session = _dbContext.AttendanceSessions
                .SingleOrDefault(s => s.Id == Base36.Decode(code));

            if (session == null)
                return NotFound();

            var user = HttpContext.User.GetUpn();

            if (session.Instructor != user)
                return Forbid();

            Session = session;
            
            return Page();
        }
        
        public IActionResult OnPostExport()
        {
            if (!ModelState.IsValid)  // TODO: make sure SessionId=";;lfs" will not crash server
                return BadRequest();
            
            var user = HttpContext.User.GetUpn();

            return _exportHelper.HandleExport(ExportParams, user);
        }
    }
}

Pages/AttendanceSessions.cshtml.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using baam.Helpers;
using baam.Model.Api;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AttendanceSession = baam.Model.Db.AttendanceSession;

namespace baam.Pages
{
    public class AttendanceSessions : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly ExportHelper _exportHelper;

        public AttendanceSessions(ApplicationDbContext db, ExportHelper exportHelper)
        {
            _db = db;
            _exportHelper = exportHelper;
        }

        public ImmutableArray<(int id, string code, DateTime date, string title, int numberOfPeople, int numberOfStages)> Items { get; set; }

        public void OnGet()
        {
            var user = HttpContext.User.GetUpn();

            Items = _db.AttendanceSessions.Where(s => !s.Running && s.Instructor == user)
                .OrderByDescending(s => s.StartDate)
                .Select(s => new {s.Id, s.StartDate, s.Title, 
                    NumberOfPeople = s.Attendance.GroupBy(a => a.Student).Count(), s.StagesCompleted})
                .AsEnumerable()
                .Select(s => (s.Id, Base36.Encode(s.Id), s.StartDate, s.Title, s.NumberOfPeople, s.StagesCompleted))
                .ToImmutableArray();
        }

        [BindProperty] 
        public ExportParams ExportParams { get; set; } = null!;
        
        public IActionResult OnPostExport()
        {
            if (!ModelState.IsValid)  // TODO: make sure SessionId=";;lfs" will not crash server
                return BadRequest();
            
            var user = HttpContext.User.GetUpn();

            return _exportHelper.HandleExport(ExportParams, user);
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace baam.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; } = null!;

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Feedback.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace baam.Pages
{
    public class Feedback : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace baam.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public string UserId { get; set; } = null!;
        
        public void OnGet()
        {
            UserId = HttpContext.User.GetUpn();
            
            _logger.LogInformation($"User: {UserId}");
        }
    }
}

Pages/MarkedSuccessfully.cshtml.cs
using System;
using System.Collections.Immutable;
using System.Linq;
using baam.Model.Db;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace baam.Pages
{
    public class MarkedSuccessfully : PageModel
    {
        private readonly ApplicationDbContext _db;

        public MarkedSuccessfully(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public AttendanceSession Session { get; private set; } = null!;
        
        public ImmutableArray<(string email, ImmutableArray<bool> marks)> AttendanceMarks { get; set; }
        
        public IActionResult OnGet(string code)
        {
            var user = HttpContext.User.GetUpn();
            
            var marks = _db.AttendanceMarks.Where(m =>
                    m.SessionId == Base36.Decode(code)
                    && m.Stage ==
                    m.Session.StagesCompleted - (m.Session.Running ? 0 : 1))
                .OrderBy(m => m.Time)
                .Include(m => m.Session)
                .ToArray();

            var index = -1;
            
            for (var i = 0; i < marks.Length; i++)
                if (marks[i].Student == user)
                    index = i;

            if (index == -1)
                return NotFound();

            var take = Math.Min(index + 1, 6);
            var skip = index - take + 1;

            marks = marks.Skip(skip).Take(take).ToArray();

            Session = marks[0].Session;

            AttendanceMarks = marks
                .GroupBy(m => m.Student)
                .OrderBy(g => g.First().Time)
                .Select(g => (g.Key,
                        Enumerable.Range(0, Session.StagesStarted)
                            .Select(s => g.Any(m => m.Stage == s))
                            .ToImmutableArray()
                    )
                ).ToImmutableArray();

            return Page();
        }
    }
}

Pages/MobileApp.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace baam.Pages
{
    public class MobileApp : PageModel
    {
    }
}

Pages/AttendanceSession.cshtml
@page "{code}"
@model AttendanceSessionModel

@{
    ViewData["Title"] = "Attendance Session view";
}

<div class="modal fade" id="export_modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document"><div class="modal-content">
		<form id="export_form" asp-page-handler="export" target="_blank" method="post">
			<input id="form_session_id" asp-for="ExportParams.SessionId" type="hidden" value="">
		
			<div class="modal-header">
				<h5 class="modal-title">Exporting attendance</h5>
			</div>
			<div class="modal-body">
				<div class="form-group">    
	                <label for="inp-exporttype">Export type:</label>
	                <select asp-for="ExportParams.ExportType" class="form-control" id="inp-exporttype">
	                  <option value="Moodle">Moodle CSV</option>
	                  <option value="Txt">Plain TXT</option>
	                  <option value="Raw">Raw CSV</option>
	                </select>
	            </div>
	            <div class="form-group" id="fg-attendancecondition">    
	                <label for="inp-attendancecondition">Presence condition:</label>
	                <select asp-for="ExportParams.AttendanceCondition" class="form-control" id="inp-attendancecondition">
	                  <option value="AtLeastOneStage">Was on at least one stage</option>
	                  <option value="AllStages">Was on all stages</option>
	                </select>
	            </div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" id="btn-export" class="btn btn-primary">Export</button>
			</div>
		</form>
	</div></div>
</div>

<div class="container flex-column d-flex" style="flex: 1">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-session-name">Session Name</span>
        </div>
        <input id="inp-session-name" type="text" class="form-control" aria-label="Session Name" 
               aria-describedby="inputGroup-session-name" value="@Model.Session.Title">
        <div class="input-group-append">
            <button id="btn-save-session-name" class="btn btn-primary">Save Name</button>
        </div>
    </div>
    <div class="input-group mb-3">
        <button id="btn-delete" class="btn btn-outline-danger mr-1">Delete</button>
        <form action="/AddSessionStage/@Model.Session.SessionCode" method="POST">
            <button type="submit" id="btn-recheck" class="btn btn-outline-secondary mr-1"
                    disabled="@(Model.Session.StagesCompleted >= 10 ? "disabled" : null)">Follow-up check</button>
        </form>
        <button id="btn-download" class="btn btn-outline-primary mr-1">Export</button>
        <span class="ml-auto mt-auto mb-auto">Taken date: @Utils.ToUserTimeString(Model.Session.StartDate)</span>
    </div>


    <div class="card student-list-card">
        <ol id="student-list" class="student-list num-student-list"></ol>
    </div>
        
    <div class="input-group add-student-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-add-student">Add student</span>
        </div>
        <div class="flex-grow-1">
            <input id="inp-add-student" type="email" class="form-control" aria-label="Add student" aria-describedby="inputGroup-add-student">
        </div>
        <div class="input-group-append">
            <button id="btn-add-student" class="btn btn-success">Add</button>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/lib/autocomplete.jquery.min.js" asp-append-version="true"></script>
    <script src="~/js/api.js" asp-append-version="true"></script>

    <script>
$(document).ready(() =>
{
    const session_code = @Html.Raw(Json.Serialize(Model.Session.SessionCode));
    
    const inp_session_name = document.getElementById("inp-session-name");
    const btn_save_session_name = document.getElementById("btn-save-session-name");
    const inp_add_student = $("#inp-add-student");
    const btn_add_student = document.getElementById("btn-add-student");
    const btn_delete = document.getElementById("btn-delete");
    
    const student_list_renderer = new StudentListRenderer(session_code, $("#student-list"), update, {});
    
    async function update() {
        const t = await baam.AttendanceSession.get(session_code);
        student_list_renderer.update(t.attendanceMarks);
        inp_session_name.innerText = t.title;
    }
    
    function onBtnSaveSessionNameClick() {
        baam.AttendanceSession.update(session_code, {'title': inp_session_name.value})
            .then(() => $.snack('success', 'Saved successfully', 1000))
            .catch(t => $.snack('error', t, 2000));
    }
    
    function onInpSessionNameKeyUp(event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            onBtnSaveSessionNameClick();
        }
    }
 
    async function addStudent(email) {
        email = email.trim();
        if (email === "") return false;

        let res = true;
        try {
            await baam.AttendanceSession.addStudent(session_code, email);
            $.snack('success', "Student added!", 1000);
        } catch (e) {
            res = false;
            $.snack('error', e, 2000);
        }
        await update();
        return res;
    }
    
    async function onBtnAddStudentClick() {
        await addStudent(inp_add_student.val());
    }
    
    function onInpAddStudentKeyUp(event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            onBtnAddStudentClick();
        }
    }
    
    async function onBtnDeleteClick(e) {
        try {
            if (confirm("Do you really want to delete this attendance session?")) {
                await baam.AttendanceSession.remove(session_code);
                document.location = "/AttendanceSessions";
            }
        } catch (e) {
            $.snack('error', e, 2000);
        }
    }
    
    let number_of_stages = 0;
    
    function start_export(page_id, _number_of_stages) {
        $("#form_session_id").val(page_id);
        number_of_stages = _number_of_stages;
        $("#inp-exporttype").change();
        $("#export_modal").modal();
    }
    
    $("#inp-exporttype").change(function() {
        const val = $(this).val();
        $("#fg-attendancecondition").attr("hidden", number_of_stages === 1 || val === "Raw");
    });
    
    $("#btn-download").click(function () {
        const t = $(this);
        start_export(@Model.Session.Id, @Model.Session.StagesCompleted);
    });
    
    $("#btn-export").click(function () {
        $("#export_modal").modal('hide');
    });
    
    btn_save_session_name.addEventListener("click", onBtnSaveSessionNameClick);
    inp_session_name.addEventListener("keyup", onInpSessionNameKeyUp);
    btn_add_student.addEventListener("click", onBtnAddStudentClick);
    inp_add_student.keyup(onInpAddStudentKeyUp);
    btn_delete.addEventListener("click", onBtnDeleteClick);
    
    make_input_selectall(inp_session_name);
    
    inp_add_student.autocomplete({
            autoselect: false,
            tabAutocomplete: false,
            hint: false,
            clearOnSelected: true,
            debug: true,
        }, [
        {
            source: function (query, cb) {
                baam.Autocomplete(query).then(r => cb(r.reverse()), 
                 err => cb([]));
            },
            displayKey: x => x,
            templates: {
                suggestion: x => x, 
            },
            cache: false
        }
    ]).on('autocomplete:selected', function(event, suggestion, dataset, context) {
        addStudent(suggestion);
        baam.Autocomplete.onSelected(suggestion);
        console.log(event, suggestion, dataset, context);
    });
    
    update().catch(t => $.snack('error', t, 2000));
});
    </script>
}

Pages/AttendanceSessions.cshtml
@page
@using baam.Model.Db
@model baam.Pages.AttendanceSessions

@{
    ViewData["Title"] = "Collected Attendance Sessions";
}

<style type="text/css">
	.btn-download > img, .btn-delete > img {
		display: block;
		margin: 0 auto;
		height: 1.5rem;
	}
	
	.table td {
		padding: 0;
	}
	
	.table > tbody > tr:hover {
		background-color: lightblue!important;
	}
</style>


<div class="modal fade" id="export_modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document"><div class="modal-content">
		<form id="export_form" asp-page-handler="export" target="_blank" method="post">
			<input id="form_session_id" asp-for="ExportParams.SessionId" type="hidden" value="">
		
			<div class="modal-header">
				<h5 class="modal-title">Exporting attendance</h5>
			</div>
			<div class="modal-body">
				<div class="form-group">    
	                <label for="inp-exporttype">Export type:</label>
	                <select asp-for="ExportParams.ExportType" class="form-control" id="inp-exporttype">
	                  <option value="Moodle">Moodle CSV</option>
	                  <option value="Txt">Plain TXT</option>
	                  <option value="Raw">Raw CSV</option>
	                </select>
	            </div>
	            <div class="form-group" id="fg-attendancecondition">    
	                <label for="inp-attendancecondition">Presence condition:</label>
	                <select asp-for="ExportParams.AttendanceCondition" class="form-control" id="inp-attendancecondition">
	                  <option value="AtLeastOneStage">Was on at least one stage</option>
	                  <option value="AllStages">Was on all stages</option>
	                </select>
	            </div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" id="btn-export" class="btn btn-primary">Export</button>
			</div>
		</form>
	</div></div>
</div>

<div class="container">
	<table class="table table-striped table-rowlink">
		<thead>
		<tr>
			<th>Date</th>
			<th>Title</th>
			<th>Number of people</th>
			<th class="text-center">Export</th>
			<th class="text-center">Delete</th>
		</tr>
		</thead>
		<tbody>
		@foreach (var item in Model.Items)
		{
			var link = Url.Page("AttendanceSession", new {item.code});
			<tr>
				<td><a href="@link">@Utils.ToUserTimeString(item.date)</a></td>
				<td><a href="@link">@item.title</a></td>
				<td><a href="@link">@item.numberOfPeople</a></td>
				<td><a class="btn-download" href="#" data-id="@item.id" data-ns="@item.numberOfStages">
					<img src="~/img/download_icon.svg"/>
				</a></td>
				<td><a class="btn-delete" href="#" data-code="@item.code">
					<img src="~/img/delete_icon.svg"/>
				</a></td>
			</tr>
		}
		</tbody>
	</table>
</div>
@section scripts {
	<script src="~/js/api.js" asp-append-version="true"></script>
	<script>
		function main() {
			let number_of_stages = 0;
			
			function start_export(page_id, _number_of_stages) {
				$("#form_session_id").val(page_id);
				number_of_stages = _number_of_stages;
				$("#inp-exporttype").change();
				$("#export_modal").modal();
			}
			
			$("#inp-exporttype").change(function() {
				const val = $(this).val();
				$("#fg-attendancecondition").attr("hidden", number_of_stages === 1 || val === "Raw");
			});
			
			$(".btn-download").click(function () {
				const t = $(this);
				start_export(t.data("id"), t.data("ns"));
			});
			
			$("#btn-export").click(function () {
				$("#export_modal").modal('hide');
			});
			
			$(".btn-delete").click(async function () {
				try {
				const t = $(this);
					if (confirm("Do you really want to delete this attendance session?")) {
						await baam.AttendanceSession.remove(t.data("code"));
						document.location = "/AttendanceSessions";
					}
				} catch (e) {
					$.snack('error', e, 2000);
				}
			});
		}
		
		$(document).ready(main);
    </script>
}

Pages/Feedback.cshtml
@page
@model baam.Pages.Feedback

@{
    ViewData["Title"] = "Feedback";
}
<style type="text/css">
footer {
    display: block !important;
}
</style>

<div class="container text-center">
    <p class="lead">Got something to say?</p>
    <p class="lead">Feel free to contact <a href="https://t.me/DCNick3">@@DCNick3</a></p>
</div>